apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-deployment
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi
        image: 792765111837.dkr.ecr.us-east-1.amazonaws.com/fastapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80