# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.1

executors:
  docker-python-executor:
    docker:
      - image: cimg/python:3.9

  docker-awscli-executor:
    docker:
      - image: amazon/aws-cli


jobs:
  build:
    executor: docker-python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  lint:
    executor: docker-python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint

      - run:
          name: run lint
          command: |
            make lint

  push-image-to-registry:
    executor: docker-awscli-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
              yum update -y
              amazon-linux-extras install docker -y

      - run:
          name: start docker daemon
          command: |
              systemctl enable docker

      - run:
          name: build an image
          command: |
            chmod +x ./scripts/docker/build.sh
            ./scripts/docker/build.sh

      - run:
          name: push an image to registry
          command: |
            chmod +x ./scripts/docker/upload.sh
            ./scripts/docker/upload.sh




workflows:
  default:
    jobs:
    - build
    - lint:
        requires: [build]
    - push-image-to-registry:
        requires: [lint]
